-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-05 15:46:41 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE auto_insurance (
    insurance_id      VARCHAR2(10) NOT NULL,
    customer_id       NUMBER(8) NOT NULL,
    start_date        DATE NOT NULL,
    end_date          DATE NOT NULL,
    premium_amount    NUMBER(10, 2) NOT NULL,
    insurance_status  VARCHAR2(1) NOT NULL
);

COMMENT ON COLUMN auto_insurance.insurance_id IS
    'Insurance ID of auto-mobile  insurance, starts with "A", followed by 9 digits number';

COMMENT ON COLUMN auto_insurance.customer_id IS
    'Customer id';

COMMENT ON COLUMN auto_insurance.start_date IS
    'start date of auto insurance policy';

COMMENT ON COLUMN auto_insurance.end_date IS
    'end date of auto insurance policy';

COMMENT ON COLUMN auto_insurance.premium_amount IS
    'auto insurance premium amount';

COMMENT ON COLUMN auto_insurance.insurance_status IS
    'auto policy insurance status';

ALTER TABLE auto_insurance ADD CONSTRAINT auto_insurance_pk PRIMARY KEY ( insurance_id );

CREATE TABLE auto_record (
    vin           VARCHAR2(17) NOT NULL,
    insurance_id  VARCHAR2(10) NOT NULL,
    a_r_id        NUMBER(8) NOT NULL
);

COMMENT ON COLUMN auto_record.vin IS
    'vehicle identification number';

COMMENT ON COLUMN auto_record.a_r_id IS
    'auto record id';

ALTER TABLE auto_record ADD CONSTRAINT auto_record_pk PRIMARY KEY ( a_r_id );

CREATE TABLE customer (
    customer_id     NUMBER(8) NOT NULL,
    first_name      VARCHAR2(30) NOT NULL,
    last_name       VARCHAR2(30) NOT NULL,
    gender          VARCHAR2(1),
    marital_status  VARCHAR2(1) NOT NULL,
    customer_type   VARCHAR2(2) NOT NULL,
    city            VARCHAR2(30) NOT NULL,
    state           VARCHAR2(2) NOT NULL,
    street          VARCHAR2(30) NOT NULL,
    zip             VARCHAR2(5) NOT NULL
);

COMMENT ON COLUMN customer.customer_id IS
    'customer''s id';

COMMENT ON COLUMN customer.first_name IS
    'customer''s first name';

COMMENT ON COLUMN customer.last_name IS
    'customer''s last name';

COMMENT ON COLUMN customer.gender IS
    'customer''s gender, must be either “M”, or “F” representing “Male” or “Female”.If it is NULL,means not provided';

COMMENT ON COLUMN customer.marital_status IS
    'customer''s marital status, the possible data value of marital status must be either “M”, “S”, or “W”, representing “Married”, “Single”, and “Widow/Widower” respectively.';

COMMENT ON COLUMN customer.customer_type IS
    'customer type, can be auto or home or both. “A” represents Automobile Insurance customer and “H” represents Home insurance customer, "B" represents both.';

COMMENT ON COLUMN customer.city IS
    'customer''s living city';

COMMENT ON COLUMN customer.state IS
    'customers'' state';

COMMENT ON COLUMN customer.street IS
    'customers'' street';

COMMENT ON COLUMN customer.zip IS
    'Zip code';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE driver (
    license_num  VARCHAR2(16) NOT NULL,
    f_name       VARCHAR2(30) NOT NULL,
    l_name       VARCHAR2(30) NOT NULL,
    birthdate    DATE NOT NULL
);

COMMENT ON COLUMN driver.license_num IS
    'driver''s license number';

COMMENT ON COLUMN driver.f_name IS
    'driver''s first name';

COMMENT ON COLUMN driver.l_name IS
    'driver''s last  name';

COMMENT ON COLUMN driver.birthdate IS
    'driver''s birthdate';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( license_num );

CREATE TABLE home_insurance (
    insurance_id      VARCHAR2(10) NOT NULL,
    customer_id       NUMBER(8) NOT NULL,
    start_date        DATE NOT NULL,
    end_date          DATE NOT NULL,
    premium_amount    NUMBER(10, 2) NOT NULL,
    insurance_status  VARCHAR2(1) NOT NULL
);

COMMENT ON COLUMN home_insurance.insurance_id IS
    'Insurance ID of home  insurance, starts with "H", followed by 9 digits number';

COMMENT ON COLUMN home_insurance.customer_id IS
    'Customer id';

COMMENT ON COLUMN home_insurance.start_date IS
    'start date of home insurance policy';

COMMENT ON COLUMN home_insurance.end_date IS
    'end date of home insurance policy';

COMMENT ON COLUMN home_insurance.premium_amount IS
    'home insurance premium amount';

COMMENT ON COLUMN home_insurance.insurance_status IS
    'home policy insurance status. "C" for current, "P" for expired';

ALTER TABLE home_insurance ADD CONSTRAINT home_insurance_pk PRIMARY KEY ( insurance_id );

CREATE TABLE home_record (
    home_id       NUMBER(10) NOT NULL,
    insurance_id  VARCHAR2(10) NOT NULL,
    h_r_id        NUMBER(8) NOT NULL
);

COMMENT ON COLUMN home_record.home_id IS
    'HOUSE''S ID';

COMMENT ON COLUMN home_record.h_r_id IS
    'home record id';

ALTER TABLE home_record ADD CONSTRAINT home_record_pk PRIMARY KEY ( h_r_id );

CREATE TABLE insured_home (
    home_id                 NUMBER(10) NOT NULL,
    home_purchase_date      DATE NOT NULL,
    home_purchase_value     NUMBER(10, 2) NOT NULL,
    home_area               NUMBER(7) NOT NULL,
    home_type               VARCHAR2(1) NOT NULL,
    auto_fire_notification  NUMBER(1) NOT NULL,
    home_security_system    NUMBER(1) NOT NULL,
    swimming_pool           VARCHAR2(1),
    basement                NUMBER(1) NOT NULL
);

COMMENT ON COLUMN insured_home.home_id IS
    'home ID';

COMMENT ON COLUMN insured_home.home_purchase_date IS
    'home purchase date';

COMMENT ON COLUMN insured_home.home_purchase_value IS
    'home purchase value';

COMMENT ON COLUMN insured_home.home_area IS
    'home area in square feet';

COMMENT ON COLUMN insured_home.home_type IS
    'type of home, S,M,C,T representing Single family, Multi Family, Condominium, Town house respectively';

COMMENT ON COLUMN insured_home.auto_fire_notification IS
    'whether home has auto fire notification or not, 1 stands for yes, 0 stands for no';

COMMENT ON COLUMN insured_home.home_security_system IS
    'whether home has security system or not, 1 stands for yes, 0 stands for no';

COMMENT ON COLUMN insured_home.swimming_pool IS
    'whether home has swimming pool or not and which kind of pool: "I" represents Indoor, "U" represents Underground, "O" represents Overground, "M" represents Multiple';

COMMENT ON COLUMN insured_home.basement IS
    'whether home has basement or not, 1 shands for yes, 0 stands for no';

ALTER TABLE insured_home ADD CONSTRAINT insured_home_pk PRIMARY KEY ( home_id );

CREATE TABLE insured_vehicle (
    vin              VARCHAR2(17) NOT NULL,
    make_model_year  NUMBER(4) NOT NULL,
    vehicle_status   VARCHAR2(1) NOT NULL
);

COMMENT ON COLUMN insured_vehicle.vin IS
    'vehicle identification number';

COMMENT ON COLUMN insured_vehicle.make_model_year IS
    'vehicle make model year';

COMMENT ON COLUMN insured_vehicle.vehicle_status IS
    'status of the vehicle, can be one of “L”, “F”, or “O” representing “Leased”, Financed”, “and Owned’.';

ALTER TABLE insured_vehicle ADD CONSTRAINT insured_vehicle_pk PRIMARY KEY ( vin );

CREATE TABLE invoice_auto (
    invoice_id        NUMBER(8) NOT NULL,
    insurance_id      VARCHAR2(10) NOT NULL,
    invoice_date      DATE NOT NULL,
    payment_due_date  DATE NOT NULL,
    invoice_amount    NUMBER(10, 2) NOT NULL
);

COMMENT ON COLUMN invoice_auto.invoice_id IS
    'invoice id';

COMMENT ON COLUMN invoice_auto.insurance_id IS
    'Insurance ID of auto-mobile insurance, starts with "A", followed by 9 digits number';

COMMENT ON COLUMN invoice_auto.invoice_date IS
    'date of invoice';

COMMENT ON COLUMN invoice_auto.payment_due_date IS
    'payment due date';

COMMENT ON COLUMN invoice_auto.invoice_amount IS
    'invoice amount in usd';

ALTER TABLE invoice_auto ADD CONSTRAINT invoice_auto_pk PRIMARY KEY ( invoice_id );

CREATE TABLE invoice_home (
    invoice_id        NUMBER(8) NOT NULL,
    insurance_id      VARCHAR2(10) NOT NULL,
    invoice_date      DATE NOT NULL,
    payment_due_date  DATE NOT NULL,
    invoice_amount    NUMBER(10, 2) NOT NULL
);

COMMENT ON COLUMN invoice_home.invoice_id IS
    'invoice id';

COMMENT ON COLUMN invoice_home.insurance_id IS
    'Insurance ID of home  insurance, starts with "H", followed by 9 digits number';

COMMENT ON COLUMN invoice_home.invoice_date IS
    'date of invoice';

COMMENT ON COLUMN invoice_home.payment_due_date IS
    'payment due date';

COMMENT ON COLUMN invoice_home.invoice_amount IS
    'invoice amount in usd';

ALTER TABLE invoice_home ADD CONSTRAINT invoice_home_pk PRIMARY KEY ( invoice_id );

CREATE TABLE payment_auto (
    payment_id      NUMBER(8) NOT NULL,
    payment_date    DATE NOT NULL,
    payment_method  VARCHAR2(6) NOT NULL,
    invoice_id      NUMBER(8)
);

COMMENT ON COLUMN payment_auto.payment_id IS
    'payment''s ID';

COMMENT ON COLUMN payment_auto.payment_date IS
    'date of payment';

COMMENT ON COLUMN payment_auto.payment_method IS
    'payment method: "PayPal", "Credit", "Debit", "Check"';

CREATE UNIQUE INDEX payment_auto__idx ON
    payment_auto (
        invoice_id
    ASC );

ALTER TABLE payment_auto ADD CONSTRAINT payment_auto_pk PRIMARY KEY ( payment_id );

CREATE TABLE payment_home (
    payment_id      NUMBER(8) NOT NULL,
    payment_date    DATE NOT NULL,
    payment_method  VARCHAR2(6) NOT NULL,
    invoice_id      NUMBER(8)
);

COMMENT ON COLUMN payment_home.payment_id IS
    'payment''s ID';

COMMENT ON COLUMN payment_home.payment_date IS
    'date of payment';

COMMENT ON COLUMN payment_home.payment_method IS
    'payment method: "PayPal", "Credit", "Debit", "Check"';

CREATE UNIQUE INDEX payment_home__idx ON
    payment_home (
        invoice_id
    ASC );

ALTER TABLE payment_home ADD CONSTRAINT payment_home_pk PRIMARY KEY ( payment_id );

CREATE TABLE vehicle_driver (
    license_num  VARCHAR2(16) NOT NULL,
    vin          VARCHAR2(17) NOT NULL,
    ins_id       VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN vehicle_driver.license_num IS
    'driver''s license number';

COMMENT ON COLUMN vehicle_driver.vin IS
    'vehicle identification number';

COMMENT ON COLUMN vehicle_driver.ins_id IS
    'insurance id';

ALTER TABLE vehicle_driver ADD CONSTRAINT vehicle_driver_pk PRIMARY KEY ( license_num,
                                                                          vin );

ALTER TABLE auto_insurance
    ADD CONSTRAINT a_ins_cust_fk FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE auto_record
    ADD CONSTRAINT a_rcd_a_ins_fk FOREIGN KEY ( insurance_id )
        REFERENCES auto_insurance ( insurance_id );

ALTER TABLE auto_record
    ADD CONSTRAINT a_rcd_ins_vcl_fk FOREIGN KEY ( vin )
        REFERENCES insured_vehicle ( vin );

ALTER TABLE home_insurance
    ADD CONSTRAINT h_ins_cust_fk FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE home_record
    ADD CONSTRAINT h_rcd_h_ins_fk FOREIGN KEY ( insurance_id )
        REFERENCES home_insurance ( insurance_id );

ALTER TABLE home_record
    ADD CONSTRAINT h_rcd_insured_h_fk FOREIGN KEY ( home_id )
        REFERENCES insured_home ( home_id );

ALTER TABLE invoice_auto
    ADD CONSTRAINT inv_a_ins_fk FOREIGN KEY ( insurance_id )
        REFERENCES auto_insurance ( insurance_id );

ALTER TABLE invoice_home
    ADD CONSTRAINT inv_h_ins_fk FOREIGN KEY ( insurance_id )
        REFERENCES home_insurance ( insurance_id );

ALTER TABLE payment_auto
    ADD CONSTRAINT pay_a_inv_a_fk FOREIGN KEY ( invoice_id )
        REFERENCES invoice_auto ( invoice_id );

ALTER TABLE payment_home
    ADD CONSTRAINT pay_h_inv_h_fk FOREIGN KEY ( invoice_id )
        REFERENCES invoice_home ( invoice_id );

ALTER TABLE vehicle_driver
    ADD CONSTRAINT vcl_dri_dri_fk FOREIGN KEY ( license_num )
        REFERENCES driver ( license_num );

ALTER TABLE vehicle_driver
    ADD CONSTRAINT vcl_dri_isd_vcl_fk FOREIGN KEY ( vin )
        REFERENCES insured_vehicle ( vin );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             2
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
